//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Poker.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum of the Small Blind is {0} $.
        /// </summary>
        internal static string BigBlindMaxValue {
            get {
                return ResourceManager.GetString("BigBlindMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum of the Small Blind is {0}$.
        /// </summary>
        internal static string BigBlindMinValue {
            get {
                return ResourceManager.GetString("BigBlindMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Big Blind can be only round number!.
        /// </summary>
        internal static string BigBlindRoundNumber {
            get {
                return ResourceManager.GetString("BigBlindRoundNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a number only field.
        /// </summary>
        internal static string NumberOnlyField {
            get {
                return ResourceManager.GetString("NumberOnlyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would You Like To Play Again ?.
        /// </summary>
        internal static string PlayAgainMessage {
            get {
                return ResourceManager.GetString("PlayAgainMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chips : {0}.
        /// </summary>
        internal static string PlayerChips {
            get {
                return ResourceManager.GetString("PlayerChips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s Turn.
        /// </summary>
        internal static string PlayerTurn {
            get {
                return ResourceManager.GetString("PlayerTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  Wins.
        /// </summary>
        internal static string PlayerWinHand {
            get {
                return ResourceManager.GetString("PlayerWinHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must raise atleast twice as the current raise !.
        /// </summary>
        internal static string RaiseAtleastTwice {
            get {
                return ResourceManager.GetString("RaiseAtleastTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes have been saved ! They will become available the next hand you play..
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum of the Small Blind is {0} $.
        /// </summary>
        internal static string SmallBlindMaxValue {
            get {
                return ResourceManager.GetString("SmallBlindMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum of the Small Blind is {0}$.
        /// </summary>
        internal static string SmallBlindMinValue {
            get {
                return ResourceManager.GetString("SmallBlindMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Small Blind can be only round number !.
        /// </summary>
        internal static string SmallBlindRoundNumber {
            get {
                return ResourceManager.GetString("SmallBlindRoundNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Won , Congratulations !.
        /// </summary>
        internal static string WinningMessage {
            get {
                return ResourceManager.GetString("WinningMessage", resourceCulture);
            }
        }
    }
}
